[default]
SQLALCHEMY_TRACK_MODIFICATIONS=false
FLASK_APP='wsgi:application'
FLASK_RUN_PORT=5002
FLASK_ENV='development'

[development]
FLASK_ENV='development'
DEBUG="True"

[production]
FLASK_ENV="production"
